### ISSUE TITLE
Option(T).of(nil) should return None

### ISSUE THREAD

**Issue by ab310x** [dhruvrajvanshi/crystalfp#1]
currently Option(T).of(nil) was returned Some(nil).
but, I think Option(T).of(nil)   should be  None.

hash = {"a" => 10}
Option(Int32).of(hash["aaa"]?) => Some(nil)
I think it should return None.

**Comment by dhruvrajvanshi** [comment]
Nope. That would mean that Option is no longer a Monad.

For Option to be a monad,
```	
Option.of(a).bind do |x| f x end  ===  f a	
```

If Option.of(nil) is None,

```
(Option.of(nil).bind do |x| f x end) !== (f nil)
```
Because f may not even take nil as an argument.

This might sound pedantic but it's very important for Monads to follow the laws
otherwise, composition of `.bind` breaks, leading to subtle bugs.

You shouldn't mix `nil` with Option. You can write a function yourself that wraps a nil
into an Option. I may consider adding it to the library but .of has to be as it is. It corresponds directly
to Applicative `point`/`return`.

**Comment by ab310x** [comment]
Certainly it is important to follow monad lows.

``` Option(Int32).of(nil) => Some(nil) ``` 
In this case,  does this completely follow the monad lows?
If your answer is yes, we want to close this issues. 
Thanks you.

**Comment by dhruvrajvanshi** [comment]
`Option(Int32).of(nil)`
This is doesn't type check because Option(Int32).of takes an `Int32`, not `Int32?`.
So no.
However, this is correct according to Monad laws.
```crystal
Option(Int32 | Nil).of(nil) => Some(nil)
```

What you were suggesting wouldn't even work very well because of Crystal's type inference.
```
Option(T).of(nil)
```
This would be inferred as Option(T?), making it useless as you'd have to
do an if check after pattern matching to get the value.
